import { env, exports } from 'cloudflare:workers'
import { afterEach, describe, expect, it, vi } from 'vitest'

const ACCESS_HEADERS = { 'Cf-Access-Jwt-Assertion': 'admitted-by-access' }

/** Stub the D1 REST response `client.query` expects for one statement. */
function stubD1Query(results: readonly Record<string, unknown>[]): void {
  vi.stubGlobal('fetch', vi.fn(async () => Response.json({
    success: true,
    result: [{ results, success: true, meta: {} }],
  })))
}

describe('edge gateway', () => {
  afterEach(() => {
    vi.unstubAllGlobals()
  })

  it('rejects a request with no Access JWT header before touching D1 or any Durable Object', async () => {
    const fetchSpy = vi.fn()
    vi.stubGlobal('fetch', fetchSpy)
    const res = await exports.default.fetch('https://example.com/')
    expect(res.status).toBe(401)
    expect(fetchSpy).not.toHaveBeenCalled()
  })

  it('rejects an explicit /w/<id>/ Workspace with no matching D1 record', async () => {
    stubD1Query([])
    const res = await exports.default.fetch('https://example.com/w/nonexistent-workspace/', { headers: ACCESS_HEADERS })
    expect(res.status).toBe(404)
  })

  it('returns a distinct failure status when the D1 existence check itself fails for an explicit /w/<id>/ Workspace', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => { throw new Error('network unreachable') }))
    const res = await exports.default.fetch('https://example.com/w/some-workspace/', { headers: ACCESS_HEADERS })
    expect(res.status).toBe(502)
  })

  it('never touches D1 for the DEFAULT_WORKSPACE_ID fallback path: it names this deployment\'s one Container slot, not a Workspace record to verify', async () => {
    // Real Workspace ids are randomUUID()-generated by dsh-workspace, so a
    // literal configured DEFAULT_WORKSPACE_ID never equals one — verifying
    // it against the D1 registry would permanently 404 a fresh
    // single-Workspace deployment before its first Workspace ever exists.
    // The request reaches real Durable Object/Container routing instead of
    // stopping at a D1 check — proven by it failing on Containers not being
    // enabled under this test tool (see the package README's Known
    // Limitations and cloudflare/workers-sdk#10408), not on any D1 call.
    const fetchSpy = vi.fn()
    vi.stubGlobal('fetch', fetchSpy)
    await expect(exports.default.fetch('https://example.com/', { headers: ACCESS_HEADERS }))
      .rejects.toThrow('Containers have not been enabled')
    expect(fetchSpy).not.toHaveBeenCalled()
  })

  it('routes an existing Workspace id to its own Durable Object, distinct from a different Workspace id', () => {
    // Session affinity is Durable Object naming, not gateway-owned logic: the
    // same Workspace id must always resolve to the same Durable Object id,
    // and a different id to a different one — verified directly against the
    // binding rather than through a real container fetch (see Known
    // Limitations: this suite does not start a real Container).
    const first = env.HOST_CONTAINER.idFromName('workspace-a')
    const again = env.HOST_CONTAINER.idFromName('workspace-a')
    const other = env.HOST_CONTAINER.idFromName('workspace-b')
    expect(first.toString()).toBe(again.toString())
    expect(first.toString()).not.toBe(other.toString())
  })
})
